development:
  adapter: postgresql
  host: 5432
  port: <portnumber>
  username: <username>
  password: <password>
  database: geowiki_dev

production:
  adapter: postgresql
  host: 5432
  port: <portnumber>
  username: <username>
  password: <password>
  database: geowiki_prod
